import { VocabularyItem, DirectionItem } from './types';

export const VOCABULARY: VocabularyItem[] = [
  { id: '1', en: 'swim', es: 'nadar', icon: 'Waves' },
  { id: '2', en: 'climb', es: 'escalar', icon: 'Mountain' },
  { id: '3', en: 'catch', es: 'atrapar', icon: 'Hand' },
  { id: '4', en: 'throw', es: 'lanzar', icon: 'MoveUp' },
  { id: '5', en: 'sing', es: 'cantar', icon: 'Mic' },
  { id: '6', en: 'dance', es: 'bailar', icon: 'Music' },
  { id: '7', en: 'draw', es: 'dibujar', icon: 'Pencil' },
  { id: '8', en: 'ride a bike', es: 'montar en bici', icon: 'Bike' },
  { id: '9', en: 'run', es: 'correr', icon: 'Zap' },
  { id: '10', en: 'jump', es: 'saltar', icon: 'ArrowUpCircle' },
  { id: '11', en: 'walk', es: 'caminar', icon: 'Footprints' },
  { id: '12', en: 'read', es: 'leer', icon: 'BookOpen' },
  { id: '13', en: 'write', es: 'escribir', icon: 'Pen' },
  { id: '14', en: 'listen', es: 'escuchar', icon: 'Headphones' },
  { id: '15', en: 'look', es: 'mirar', icon: 'Eye' },
  { id: '16', en: 'speak', es: 'hablar', icon: 'Megaphone' },
  { id: '17', en: 'play', es: 'jugar', icon: 'Gamepad2' },
  { id: '18', en: 'eat', es: 'comer', icon: 'Utensils' },
  { id: '19', en: 'drink', es: 'beber', icon: 'CupSoda' },
  { id: '20', en: 'sleep', es: 'dormir', icon: 'Bed' },
  { id: '21', en: 'cat', es: 'gato', icon: 'Cat' },
  { id: '22', en: 'dog', es: 'perro', icon: 'Dog' },
  { id: '23', en: 'bird', es: 'pájaro', icon: 'Bird' },
  { id: '24', en: 'fish', es: 'pez', icon: 'Fish' },
  { id: '25', en: 'turtle', es: 'tortuga', icon: 'Turtle' },
  { id: '26', en: 'rabbit', es: 'conejo', icon: 'Rabbit' },
  { id: '27', en: 'snail', es: 'caracol', icon: 'Snail' },
  { id: '28', en: 'bug', es: 'bicho', icon: 'Bug' },
  { id: '29', en: 'mouse', es: 'ratón', icon: 'Mouse' },
  { id: '30', en: 'pig', es: 'cerdo', icon: 'Pig' },
  { id: '31', en: 'spider', es: 'araña', icon: 'Spider' },
  { id: '32', en: 'lion', es: 'león', icon: 'Sun' },
  { id: '33', en: 'elephant', es: 'elefante', icon: 'Cloud' },
  { id: '34', en: 'monkey', es: 'mono', icon: 'Smile' },
  { id: '35', en: 'bear', es: 'oso', icon: 'Snowflake' },
  { id: '36', en: 'apple', es: 'manzana', icon: 'Apple' },
  { id: '37', en: 'banana', es: 'plátano', icon: 'Banana' },
  { id: '38', en: 'carrot', es: 'zanahoria', icon: 'Carrot' },
  { id: '39', en: 'cherry', es: 'cereza', icon: 'Cherry' },
  { id: '40', en: 'grape', es: 'uva', icon: 'Grape' },
  { id: '41', en: 'lemon', es: 'limón', icon: 'Lemon' },
  { id: '42', en: 'orange', es: 'naranja', icon: 'Citrus' },
  { id: '43', en: 'pizza', es: 'pizza', icon: 'Pizza' },
  { id: '44', en: 'cake', es: 'pastel', icon: 'Cake' },
  { id: '45', en: 'ice cream', es: 'helado', icon: 'IceCream' },
  { id: '46', en: 'bread', es: 'pan', icon: 'Croissant' },
  { id: '47', en: 'cheese', es: 'queso', icon: 'Cheese' },
  { id: '48', en: 'milk', es: 'leche', icon: 'Milk' },
  { id: '49', en: 'water', es: 'agua', icon: 'Droplet' },
  { id: '50', en: 'sun', es: 'sol', icon: 'Sun' },
  { id: '51', en: 'moon', es: 'luna', icon: 'Moon' },
  { id: '52', en: 'star', es: 'estrella', icon: 'Star' },
  { id: '53', en: 'cloud', es: 'nube', icon: 'Cloud' },
  { id: '54', en: 'rain', es: 'lluvia', icon: 'CloudRain' },
  { id: '55', en: 'snow', es: 'nieve', icon: 'Snowflake' },
  { id: '56', en: 'wind', es: 'viento', icon: 'Wind' },
  { id: '57', en: 'storm', es: 'tormenta', icon: 'CloudLightning' },
  { id: '58', en: 'tree', es: 'árbol', icon: 'TreePine' },
  { id: '59', en: 'leaf', es: 'hoja', icon: 'Leaf' },
  { id: '60', en: 'flower', es: 'flor', icon: 'Flower' },
  { id: '61', en: 'mountain', es: 'montaña', icon: 'Mountain' },
  { id: '62', en: 'ocean', es: 'océano', icon: 'Waves' },
  { id: '63', en: 'river', es: 'río', icon: 'Waves' },
  { id: '64', en: 'fire', es: 'fuego', icon: 'Flame' },
  { id: '65', en: 'red', es: 'rojo', icon: 'Palette' },
  { id: '66', en: 'blue', es: 'azul', icon: 'Palette' },
  { id: '67', en: 'green', es: 'verde', icon: 'Palette' },
  { id: '68', en: 'yellow', es: 'amarillo', icon: 'Palette' },
  { id: '69', en: 'black', es: 'negro', icon: 'Palette' },
  { id: '70', en: 'white', es: 'blanco', icon: 'Palette' },
  { id: '71', en: 'pink', es: 'rosa', icon: 'Palette' },
  { id: '72', en: 'hat', es: 'sombrero', icon: 'Crown' },
  { id: '73', en: 'shirt', es: 'camisa', icon: 'Shirt' },
  { id: '74', en: 'pants', es: 'pantalones', icon: 'Scissors' },
  { id: '75', en: 'shoes', es: 'zapatos', icon: 'Footprints' },
  { id: '76', en: 'glasses', es: 'gafas', icon: 'Glasses' },
  { id: '77', en: 'umbrella', es: 'paraguas', icon: 'Umbrella' },
  { id: '78', en: 'car', es: 'coche', icon: 'Car' },
  { id: '79', en: 'bus', es: 'autobús', icon: 'Bus' },
  { id: '80', en: 'train', es: 'tren', icon: 'Train' },
  { id: '81', en: 'plane', es: 'avión', icon: 'Plane' },
  { id: '82', en: 'rocket', es: 'cohete', icon: 'Rocket' },
  { id: '83', en: 'ship', es: 'barco', icon: 'Ship' },
  { id: '84', en: 'boat', es: 'barca', icon: 'Sailboat' },
  { id: '85', en: 'house', es: 'casa', icon: 'Home' },
  { id: '86', en: 'school', es: 'escuela', icon: 'School' },
  { id: '87', en: 'hospital', es: 'hospital', icon: 'Hospital' },
  { id: '88', en: 'park', es: 'parque', icon: 'TentTree' },
  { id: '89', en: 'happy', es: 'feliz', icon: 'Smile' },
  { id: '90', en: 'sad', es: 'triste', icon: 'Frown' },
  { id: '91', en: 'angry', es: 'enfadado', icon: 'Frown' },
  { id: '92', en: 'scared', es: 'asustado', icon: 'Ghost' },
  { id: '93', en: 'tired', es: 'cansado', icon: 'BatteryLow' },
  { id: '94', en: 'hot', es: 'caliente', icon: 'Flame' },
  { id: '95', en: 'cold', es: 'frío', icon: 'Snowflake' },
  { id: '96', en: 'big', es: 'grande', icon: 'Maximize' },
  { id: '97', en: 'small', es: 'pequeño', icon: 'Minimize' },
  { id: '98', en: 'fast', es: 'rápido', icon: 'Zap' },
  { id: '99', en: 'slow', es: 'lento', icon: 'Turtle' },
  { id: '100', en: 'stop', es: 'parar', icon: 'OctagonStop' }
];

export const DIRECTIONS: DirectionItem[] = [
  { id: 'up', en: 'up', es: 'arriba', icon: 'ArrowUp' },
  { id: 'down', en: 'down', es: 'abajo', icon: 'ArrowDown' },
  { id: 'left', en: 'left', es: 'izquierda', icon: 'ArrowLeft' },
  { id: 'right', en: 'right', es: 'derecha', icon: 'ArrowRight' },
];

export const PLACES = [
  { id: 'forest', en: 'forest', es: 'bosque', icon: 'Trees' },
  { id: 'mountains', en: 'mountains', es: 'montañas', icon: 'MountainSnow' },
  { id: 'forest_park', en: 'forest park', es: 'parque natural', icon: 'TentTree' },
  { id: 'lake', en: 'lake', es: 'lago', icon: 'Waves' },
];
